apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx # 部署的名称
spec:
  selector:
    matchLabels:
      app: nginx # 匹配标签
  replicas: 5 # 指定运行 5 个副本的 Nginx Pod
  template:
    metadata:
      labels:
        app: nginx # 标签，供服务选择器匹配
    spec:
      containers:
      - name: nginx
        image: nginx # 使用官方 Nginx 镜像
        ports:
        - containerPort: 80 # 容器内部暴露的端口

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service # 服务的名称
spec:
  type: NodePort # 使用 NodePort 类型的服务，将服务暴露在 Kubernetes 节点的一个端口上
  selector:
    app: nginx # 匹配 Nginx Pod 的标签
  ports:
  - port: 80 # 服务暴露的端口
    targetPort: 80 # 容器内部的目标端口
    nodePort: 30080 # 节点上的端口，通过这个端口可以从外部访问 Nginx。Kubernetes 中 nodePort 的有效范围是 30000 到 32767